/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.school21.smartcalc.forms;

/**
 *
 * @author user
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        button_plot = new javax.swing.JButton();
        button_x = new javax.swing.JButton();
        button_bracket_left = new javax.swing.JButton();
        button_bracket_right = new javax.swing.JButton();
        button_erase = new javax.swing.JButton();
        button_backspace = new javax.swing.JButton();
        button_e = new javax.swing.JButton();
        button_pi = new javax.swing.JButton();
        button_mod = new javax.swing.JButton();
        button_sqrt = new javax.swing.JButton();
        button_pow = new javax.swing.JButton();
        button_div = new javax.swing.JButton();
        button_sin = new javax.swing.JButton();
        button_asin = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_mul = new javax.swing.JButton();
        button_cos = new javax.swing.JButton();
        button_acos = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_sub = new javax.swing.JButton();
        button_tan = new javax.swing.JButton();
        button_atan = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_sum = new javax.swing.JButton();
        button_ln = new javax.swing.JButton();
        button_log = new javax.swing.JButton();
        button_E = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_dot = new javax.swing.JButton();
        button_equals = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_main = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setAlignmentX(0.0F);
        jTabbedPane1.setAlignmentY(0.0F);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);

        button_plot.setText("PLOT");
        button_plot.setAlignmentY(0.0F);
        button_plot.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_plot.setMaximumSize(new java.awt.Dimension(0, 0));
        button_plot.setMinimumSize(new java.awt.Dimension(60, 30));
        button_plot.setPreferredSize(new java.awt.Dimension(60, 30));

        button_x.setText("x");
        button_x.setAlignmentY(0.0F);
        button_x.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_x.setMaximumSize(new java.awt.Dimension(0, 0));
        button_x.setMinimumSize(new java.awt.Dimension(60, 30));
        button_x.setPreferredSize(new java.awt.Dimension(60, 30));
        button_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_xActionPerformed(evt);
            }
        });

        button_bracket_left.setText("(");
        button_bracket_left.setAlignmentY(0.0F);
        button_bracket_left.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_bracket_left.setMaximumSize(new java.awt.Dimension(0, 0));
        button_bracket_left.setMinimumSize(new java.awt.Dimension(60, 30));
        button_bracket_left.setPreferredSize(new java.awt.Dimension(60, 30));
        button_bracket_left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bracket_leftActionPerformed(evt);
            }
        });

        button_bracket_right.setText(")");
        button_bracket_right.setAlignmentY(0.0F);
        button_bracket_right.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_bracket_right.setMaximumSize(new java.awt.Dimension(0, 0));
        button_bracket_right.setMinimumSize(new java.awt.Dimension(60, 30));
        button_bracket_right.setPreferredSize(new java.awt.Dimension(60, 30));
        button_bracket_right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bracket_rightActionPerformed(evt);
            }
        });

        button_erase.setText("C");
        button_erase.setAlignmentY(0.0F);
        button_erase.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_erase.setMaximumSize(new java.awt.Dimension(0, 0));
        button_erase.setMinimumSize(new java.awt.Dimension(60, 30));
        button_erase.setPreferredSize(new java.awt.Dimension(60, 30));
        button_erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_eraseActionPerformed(evt);
            }
        });

        button_backspace.setText("<--");
        button_backspace.setAlignmentY(0.0F);
        button_backspace.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_backspace.setMaximumSize(new java.awt.Dimension(0, 0));
        button_backspace.setMinimumSize(new java.awt.Dimension(60, 30));
        button_backspace.setPreferredSize(new java.awt.Dimension(60, 30));
        button_backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backspaceActionPerformed(evt);
            }
        });

        button_e.setText("e");
        button_e.setAlignmentY(0.0F);
        button_e.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_e.setMaximumSize(new java.awt.Dimension(0, 0));
        button_e.setMinimumSize(new java.awt.Dimension(60, 30));
        button_e.setPreferredSize(new java.awt.Dimension(60, 30));
        button_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_eActionPerformed(evt);
            }
        });

        button_pi.setText("π");
        button_pi.setToolTipText("");
        button_pi.setAlignmentY(0.0F);
        button_pi.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_pi.setMaximumSize(new java.awt.Dimension(0, 0));
        button_pi.setMinimumSize(new java.awt.Dimension(60, 30));
        button_pi.setPreferredSize(new java.awt.Dimension(60, 30));
        button_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_piActionPerformed(evt);
            }
        });

        button_mod.setText("Mod");
        button_mod.setAlignmentY(0.0F);
        button_mod.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_mod.setMaximumSize(new java.awt.Dimension(0, 0));
        button_mod.setMinimumSize(new java.awt.Dimension(60, 30));
        button_mod.setPreferredSize(new java.awt.Dimension(60, 30));
        button_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_modActionPerformed(evt);
            }
        });

        button_sqrt.setText("√");
        button_sqrt.setAlignmentY(0.0F);
        button_sqrt.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_sqrt.setMaximumSize(new java.awt.Dimension(0, 0));
        button_sqrt.setMinimumSize(new java.awt.Dimension(60, 30));
        button_sqrt.setPreferredSize(new java.awt.Dimension(60, 30));
        button_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sqrtActionPerformed(evt);
            }
        });

        button_pow.setText("^");
        button_pow.setAlignmentY(0.0F);
        button_pow.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_pow.setMaximumSize(new java.awt.Dimension(0, 0));
        button_pow.setMinimumSize(new java.awt.Dimension(60, 30));
        button_pow.setPreferredSize(new java.awt.Dimension(60, 30));
        button_pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_powActionPerformed(evt);
            }
        });

        button_div.setText("÷");
        button_div.setAlignmentY(0.0F);
        button_div.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_div.setMaximumSize(new java.awt.Dimension(0, 0));
        button_div.setMinimumSize(new java.awt.Dimension(60, 30));
        button_div.setPreferredSize(new java.awt.Dimension(60, 30));
        button_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_divActionPerformed(evt);
            }
        });

        button_sin.setText("sin");
        button_sin.setAlignmentY(0.0F);
        button_sin.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_sin.setMaximumSize(new java.awt.Dimension(0, 0));
        button_sin.setMinimumSize(new java.awt.Dimension(60, 30));
        button_sin.setPreferredSize(new java.awt.Dimension(60, 30));
        button_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sinActionPerformed(evt);
            }
        });

        button_asin.setText("asin");
        button_asin.setAlignmentY(0.0F);
        button_asin.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_asin.setMaximumSize(new java.awt.Dimension(0, 0));
        button_asin.setMinimumSize(new java.awt.Dimension(60, 30));
        button_asin.setPreferredSize(new java.awt.Dimension(60, 30));
        button_asin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_asinActionPerformed(evt);
            }
        });

        button_7.setText("7");
        button_7.setAlignmentY(0.0F);
        button_7.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_7.setMaximumSize(new java.awt.Dimension(0, 0));
        button_7.setMinimumSize(new java.awt.Dimension(60, 30));
        button_7.setPreferredSize(new java.awt.Dimension(60, 30));
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        button_8.setText("8");
        button_8.setAlignmentY(0.0F);
        button_8.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_8.setMaximumSize(new java.awt.Dimension(0, 0));
        button_8.setMinimumSize(new java.awt.Dimension(60, 30));
        button_8.setPreferredSize(new java.awt.Dimension(60, 30));
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_9.setText("9");
        button_9.setAlignmentY(0.0F);
        button_9.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_9.setMaximumSize(new java.awt.Dimension(0, 0));
        button_9.setMinimumSize(new java.awt.Dimension(60, 30));
        button_9.setPreferredSize(new java.awt.Dimension(60, 30));
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });

        button_mul.setText("×");
        button_mul.setAlignmentY(0.0F);
        button_mul.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_mul.setMaximumSize(new java.awt.Dimension(0, 0));
        button_mul.setMinimumSize(new java.awt.Dimension(60, 30));
        button_mul.setPreferredSize(new java.awt.Dimension(60, 30));
        button_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mulActionPerformed(evt);
            }
        });

        button_cos.setText("cos");
        button_cos.setAlignmentY(0.0F);
        button_cos.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_cos.setMaximumSize(new java.awt.Dimension(0, 0));
        button_cos.setMinimumSize(new java.awt.Dimension(60, 30));
        button_cos.setPreferredSize(new java.awt.Dimension(60, 30));
        button_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cosActionPerformed(evt);
            }
        });

        button_acos.setText("acos");
        button_acos.setAlignmentY(0.0F);
        button_acos.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_acos.setMaximumSize(new java.awt.Dimension(0, 0));
        button_acos.setMinimumSize(new java.awt.Dimension(60, 30));
        button_acos.setPreferredSize(new java.awt.Dimension(60, 30));
        button_acos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_acosActionPerformed(evt);
            }
        });

        button_4.setText("4");
        button_4.setAlignmentY(0.0F);
        button_4.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_4.setMaximumSize(new java.awt.Dimension(0, 0));
        button_4.setMinimumSize(new java.awt.Dimension(60, 30));
        button_4.setPreferredSize(new java.awt.Dimension(60, 30));
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        button_5.setText("5");
        button_5.setAlignmentY(0.0F);
        button_5.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_5.setMaximumSize(new java.awt.Dimension(0, 0));
        button_5.setMinimumSize(new java.awt.Dimension(60, 30));
        button_5.setPreferredSize(new java.awt.Dimension(60, 30));
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_6.setText("6");
        button_6.setAlignmentY(0.0F);
        button_6.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_6.setMaximumSize(new java.awt.Dimension(0, 0));
        button_6.setMinimumSize(new java.awt.Dimension(60, 30));
        button_6.setPreferredSize(new java.awt.Dimension(60, 30));
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_sub.setText("-");
        button_sub.setAlignmentY(0.0F);
        button_sub.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_sub.setMaximumSize(new java.awt.Dimension(0, 0));
        button_sub.setMinimumSize(new java.awt.Dimension(60, 30));
        button_sub.setPreferredSize(new java.awt.Dimension(60, 30));
        button_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_subActionPerformed(evt);
            }
        });

        button_tan.setText("tan");
        button_tan.setAlignmentY(0.0F);
        button_tan.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_tan.setMaximumSize(new java.awt.Dimension(0, 0));
        button_tan.setMinimumSize(new java.awt.Dimension(60, 30));
        button_tan.setPreferredSize(new java.awt.Dimension(60, 30));
        button_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tanActionPerformed(evt);
            }
        });

        button_atan.setText("atan");
        button_atan.setAlignmentY(0.0F);
        button_atan.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_atan.setMaximumSize(new java.awt.Dimension(0, 0));
        button_atan.setMinimumSize(new java.awt.Dimension(60, 30));
        button_atan.setPreferredSize(new java.awt.Dimension(60, 30));
        button_atan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_atanActionPerformed(evt);
            }
        });

        button_1.setText("1");
        button_1.setAlignmentY(0.0F);
        button_1.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_1.setMaximumSize(new java.awt.Dimension(0, 0));
        button_1.setMinimumSize(new java.awt.Dimension(60, 30));
        button_1.setPreferredSize(new java.awt.Dimension(60, 30));
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_2.setText("2");
        button_2.setAlignmentY(0.0F);
        button_2.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_2.setMaximumSize(new java.awt.Dimension(0, 0));
        button_2.setMinimumSize(new java.awt.Dimension(60, 30));
        button_2.setPreferredSize(new java.awt.Dimension(60, 30));
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_3.setText("3");
        button_3.setAlignmentY(0.0F);
        button_3.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_3.setMaximumSize(new java.awt.Dimension(0, 0));
        button_3.setMinimumSize(new java.awt.Dimension(60, 30));
        button_3.setPreferredSize(new java.awt.Dimension(60, 30));
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_sum.setText("+");
        button_sum.setAlignmentY(0.0F);
        button_sum.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_sum.setMaximumSize(new java.awt.Dimension(0, 0));
        button_sum.setMinimumSize(new java.awt.Dimension(60, 30));
        button_sum.setPreferredSize(new java.awt.Dimension(60, 30));
        button_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sumActionPerformed(evt);
            }
        });

        button_ln.setText("ln");
        button_ln.setAlignmentY(0.0F);
        button_ln.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_ln.setMaximumSize(new java.awt.Dimension(0, 0));
        button_ln.setMinimumSize(new java.awt.Dimension(60, 30));
        button_ln.setPreferredSize(new java.awt.Dimension(60, 30));
        button_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_lnActionPerformed(evt);
            }
        });

        button_log.setText("log");
        button_log.setAlignmentY(0.0F);
        button_log.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_log.setMaximumSize(new java.awt.Dimension(0, 0));
        button_log.setMinimumSize(new java.awt.Dimension(60, 30));
        button_log.setPreferredSize(new java.awt.Dimension(60, 30));
        button_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logActionPerformed(evt);
            }
        });

        button_E.setText("E");
        button_E.setAlignmentY(0.0F);
        button_E.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_E.setMaximumSize(new java.awt.Dimension(0, 0));
        button_E.setMinimumSize(new java.awt.Dimension(60, 30));
        button_E.setPreferredSize(new java.awt.Dimension(60, 30));
        button_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EActionPerformed(evt);
            }
        });

        button_0.setText("0");
        button_0.setAlignmentY(0.0F);
        button_0.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_0.setMaximumSize(new java.awt.Dimension(0, 0));
        button_0.setMinimumSize(new java.awt.Dimension(60, 30));
        button_0.setPreferredSize(new java.awt.Dimension(60, 30));
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_0ActionPerformed(evt);
            }
        });

        button_dot.setText(".");
        button_dot.setAlignmentY(0.0F);
        button_dot.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_dot.setMaximumSize(new java.awt.Dimension(0, 0));
        button_dot.setMinimumSize(new java.awt.Dimension(60, 30));
        button_dot.setPreferredSize(new java.awt.Dimension(60, 30));
        button_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dotActionPerformed(evt);
            }
        });

        button_equals.setText("=");
        button_equals.setAlignmentY(0.0F);
        button_equals.setMargin(new java.awt.Insets(2, 5, 3, 5));
        button_equals.setMaximumSize(new java.awt.Dimension(0, 0));
        button_equals.setMinimumSize(new java.awt.Dimension(60, 30));
        button_equals.setPreferredSize(new java.awt.Dimension(60, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_sin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_asin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(button_plot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_bracket_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_bracket_right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_erase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_backspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(button_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_pi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_pow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(button_cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_acos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(button_tan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_atan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(button_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_equals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_plot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_bracket_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_bracket_right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_erase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_backspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_sin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_asin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_acos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_tan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_atan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_equals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setAlignmentX(0.0F);
        jPanel6.setAlignmentY(0.0F);

        jLabel1.setText("Number of decimal places");
        jLabel1.setAlignmentY(0.0F);

        jSpinner1.setAlignmentX(0.0F);
        jSpinner1.setAlignmentY(0.0F);
        jSpinner1.setMaximumSize(new java.awt.Dimension(0, 0));
        jSpinner1.setMinimumSize(new java.awt.Dimension(60, 22));
        jSpinner1.setPreferredSize(new java.awt.Dimension(60, 22));

        jCheckBox1.setAlignmentY(0.0F);
        jCheckBox1.setLabel("Show trailing zeroes");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jCheckBox1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jCheckBox1))
        );

        jPanel7.setAlignmentX(0.0F);
        jPanel7.setAlignmentY(0.0F);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setFocusCycleRoot(true);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setRowHeaderView(null);

        display_main.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 18)); // NOI18N
        display_main.setText("jTextField1");
        jScrollPane1.setViewportView(display_main);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAlignmentX(0.0F);
        jScrollPane2.setAlignmentY(0.0F);

        jTextPane1.setAlignmentX(0.0F);
        jTextPane1.setAlignmentY(0.0F);
        jScrollPane2.setViewportView(jTextPane1);

        jButton37.setText("jButton37");
        jButton37.setAlignmentY(0.0F);
        jButton37.setMaximumSize(new java.awt.Dimension(60, 30));
        jButton37.setMinimumSize(new java.awt.Dimension(60, 30));
        jButton37.setPreferredSize(new java.awt.Dimension(60, 30));

        jButton38.setText("jButton38");
        jButton38.setAlignmentY(0.0F);
        jButton38.setMaximumSize(new java.awt.Dimension(60, 30));
        jButton38.setMinimumSize(new java.awt.Dimension(60, 30));
        jButton38.setPreferredSize(new java.awt.Dimension(60, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel1);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Credit calculator", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
        display_main.setText(display_main.getText() + "7"); // TODO add your handling code here:
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
        display_main.setText(display_main.getText() + "8"); // TODO add your handling code here:
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
        display_main.setText(display_main.getText() + "9"); // TODO add your handling code here:
    }//GEN-LAST:event_button_9ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
        display_main.setText(display_main.getText() + "4"); // TODO add your handling code here:
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
        display_main.setText(display_main.getText() + "5");        // TODO add your handling code here:
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
        display_main.setText(display_main.getText() + "6");        // TODO add your handling code here:
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        display_main.setText(display_main.getText() + "1");        // TODO add your handling code here:
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        display_main.setText(display_main.getText() + "2");        // TODO add your handling code here:
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
        display_main.setText(display_main.getText() + "3");        // TODO add your handling code here:
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EActionPerformed
        display_main.setText(display_main.getText() + "E");        // TODO add your handling code here:
    }//GEN-LAST:event_button_EActionPerformed

    private void button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_0ActionPerformed
        display_main.setText(display_main.getText() + "0");        // TODO add your handling code here:
    }//GEN-LAST:event_button_0ActionPerformed

    private void button_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dotActionPerformed
        display_main.setText(display_main.getText() + ".");        // TODO add your handling code here:
    }//GEN-LAST:event_button_dotActionPerformed

    private void button_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sumActionPerformed
        display_main.setText(display_main.getText() + "+");        // TODO add your handling code here:
    }//GEN-LAST:event_button_sumActionPerformed

    private void button_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_subActionPerformed
        display_main.setText(display_main.getText() + "-");        // TODO add your handling code here:
    }//GEN-LAST:event_button_subActionPerformed

    private void button_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mulActionPerformed
        display_main.setText(display_main.getText() + "×");        // TODO add your handling code here:
    }//GEN-LAST:event_button_mulActionPerformed

    private void button_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_divActionPerformed
        display_main.setText(display_main.getText() + "÷");         // TODO add your handling code here:
    }//GEN-LAST:event_button_divActionPerformed

    private void button_powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_powActionPerformed
        display_main.setText(display_main.getText() + "^");        // TODO add your handling code here:
    }//GEN-LAST:event_button_powActionPerformed

    private void button_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sqrtActionPerformed
       display_main.setText(display_main.getText() + "√(");       // TODO add your handling code here:
    }//GEN-LAST:event_button_sqrtActionPerformed

    private void button_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_modActionPerformed
       display_main.setText(display_main.getText() + "Mod"); // TODO add your handling code here:
    }//GEN-LAST:event_button_modActionPerformed

    private void button_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_piActionPerformed
      display_main.setText(display_main.getText() + "π");  // TODO add your handling code here:
    }//GEN-LAST:event_button_piActionPerformed

    private void button_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_eActionPerformed
       display_main.setText(display_main.getText() + "e");  // TODO add your handling code here:
    }//GEN-LAST:event_button_eActionPerformed

    private void button_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sinActionPerformed
        display_main.setText(display_main.getText() + "sin(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_sinActionPerformed

    private void button_asinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_asinActionPerformed
        display_main.setText(display_main.getText() + "asin(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_asinActionPerformed

    private void button_acosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_acosActionPerformed
        display_main.setText(display_main.getText() + "acos(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_acosActionPerformed

    private void button_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cosActionPerformed
        display_main.setText(display_main.getText() + "cos(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_cosActionPerformed

    private void button_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tanActionPerformed
        display_main.setText(display_main.getText() + "tan(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_tanActionPerformed

    private void button_atanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_atanActionPerformed
        display_main.setText(display_main.getText() + "atan(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_atanActionPerformed

    private void button_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_lnActionPerformed
        display_main.setText(display_main.getText() + "ln(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_lnActionPerformed

    private void button_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logActionPerformed
        display_main.setText(display_main.getText() + "log(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_logActionPerformed

    private void button_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_xActionPerformed
        display_main.setText(display_main.getText() + "x");         // TODO add your handling code here:
    }//GEN-LAST:event_button_xActionPerformed

    private void button_bracket_leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bracket_leftActionPerformed
        display_main.setText(display_main.getText() + "(");         // TODO add your handling code here:
    }//GEN-LAST:event_button_bracket_leftActionPerformed

    private void button_bracket_rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bracket_rightActionPerformed
        display_main.setText(display_main.getText() + ")");         // TODO add your handling code here:
    }//GEN-LAST:event_button_bracket_rightActionPerformed

    private void button_eraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_eraseActionPerformed
        display_main.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_button_eraseActionPerformed

    private void button_backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backspaceActionPerformed
        String text = display_main.getText();
        if (text.endsWith("asin(") || text.endsWith("acos(") || text.endsWith("atan(")) {
            display_main.setText(display_main.getText().substring(0, display_main.getText().length() - 5));
        } else if (text.endsWith("sin(") || text.endsWith("cos(") || text.endsWith("tan(") || text.endsWith("log(")){
            display_main.setText(display_main.getText().substring(0, display_main.getText().length() - 4)); 
        } else if (text.endsWith("ln(") || text.endsWith("Mod")) {
            display_main.setText(display_main.getText().substring(0, display_main.getText().length() - 3));
        } else if (text.endsWith("√(")) {
            display_main.setText(display_main.getText().substring(0, display_main.getText().length() - 2));
        } else {
            display_main.setText(display_main.getText().substring(0, display_main.getText().length() - 1));         // TODO add your handling code here:
        }
    }//GEN-LAST:event_button_backspaceActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_E;
    private javax.swing.JButton button_acos;
    private javax.swing.JButton button_asin;
    private javax.swing.JButton button_atan;
    private javax.swing.JButton button_backspace;
    private javax.swing.JButton button_bracket_left;
    private javax.swing.JButton button_bracket_right;
    private javax.swing.JButton button_cos;
    private javax.swing.JButton button_div;
    private javax.swing.JButton button_dot;
    private javax.swing.JButton button_e;
    private javax.swing.JButton button_equals;
    private javax.swing.JButton button_erase;
    private javax.swing.JButton button_ln;
    private javax.swing.JButton button_log;
    private javax.swing.JButton button_mod;
    private javax.swing.JButton button_mul;
    private javax.swing.JButton button_pi;
    private javax.swing.JButton button_plot;
    private javax.swing.JButton button_pow;
    private javax.swing.JButton button_sin;
    private javax.swing.JButton button_sqrt;
    private javax.swing.JButton button_sub;
    private javax.swing.JButton button_sum;
    private javax.swing.JButton button_tan;
    private javax.swing.JButton button_x;
    private javax.swing.JTextField display_main;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
